import Head from 'next/head'
import Link from 'next/link';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiOutlineArrowDown } from 'react-icons/ai';
import { useState } from 'react';

export default function Contact() {
    const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
        <Head>
        <title>React-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:hover:duration-300'>
        <section className=' min-h-screen'>
          <nav className=' py-10 mb-15 flex justify-between'>
            <h2 className=' uppercase text-xl text-blue-600 lg:text-2xl font-bold'>Mk Haque</h2>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=' text-2xl cursor-pointer dark:text-white dark:hover:duration-300 ' />
            </li>
            <li>
             <Link href="/" className=' hover:text-black duration-300 bg-gradient-to-r from-cyan-500 to-blue-500 text-white px-4 py-2 rounded-md ml-8'>Home</Link>
            </li>
            <li>
              <Link  href="/contact" className=' hover:text-black duration-300 bg-gradient-to-r from-cyan-500 to-blue-500 text-white px-4 py-2 rounded-md ml-8'>Contact</Link>
            </li>
          </ul>
          </nav>
          <section className='flex justify-center'>
          <button type='button' className='flex justify-center bg-cyan-500 px-3 py-4 rounded-lg'> <svg className='animate-bounce h-6 w-6 mt-1'><AiOutlineArrowDown /></svg> Developing...</button>
          </section>
          
        </section>
      </main>
      <footer className='bg-gray-700 py-9 text-center'>
          <div>
          <h4 className='text-white'>Copyright@</h4><Link href="/contact">M M Khairul Haque</Link> 
          </div>
        </footer>
    </div>
  );
}