import Head from 'next/head'
import Link from 'next/link';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillInstagram, AiFillLinkedin, AiFillGithub, AiFillDownCircle, AiFillCarryOut } from 'react-icons/ai';
import Image from 'next/image'
import deved from "../public/pic1.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import agency from "../public/d1.png";
import card from "../public/d2.png";
import nipro from "../public/d3.png";
import product from "../public/d4.png";
import travel from "../public/d5.png";
import cardProduct from "../public/d6.png";
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>React-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:hover:duration-300'>
        <section className=' min-h-screen'>
          <nav className=' py-10 mb-15 flex justify-between'>
            <a href='#' className=' uppercase text-xl text-blue-600 lg:text-2xl font-bold'>Mk Haque</a>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=' text-2xl cursor-pointer dark:text-white dark:hover:duration-300 ' />
            </li>
            <li>
             <a href="CV-2024_New.pdf" download className=' flex hover:text-black duration-300 bg-gradient-to-r from-cyan-500 to-blue-500 text-white px-4 py-2 rounded-md ml-8'><svg className=' h-6 w-6 mt-1 animate-bounce'><AiFillDownCircle /></svg>Resume</a>
            </li>
          </ul>
          </nav>
          <div className=' text-center p-10'>
            <h2 className='py-3 text-3xl text-teal-500 font-bold md:text-5xl'> M M Khairul Haque</h2>
            <p className=' text-lg font-medium leading-8 text-gray-800 md:text-xl max-w-lg mx-auto lg: max-auto dark:text-white '>Hello there!! I am Frontend Web developer & Designer from Germany.. Let's make a creative things for you.</p>
          </div>
          <div className='flex justify-center text-5xl gap-16 mb-10 '>
            <a className='hover:text-blue-500 hover:scale-125 duration-300 dark:text-white dark:hover:text-teal-500' href='#'><AiFillInstagram/></a>
            <a className='hover:text-blue-500 hover:scale-125 duration-300 dark:text-white dark:hover:text-teal-500' href='#'><AiFillLinkedin/></a>
            <a className='hover:text-blue-500 hover:scale-125 duration-300 dark:text-white dark:hover:text-teal-500' href='#'><AiFillGithub/></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 py-5 overflow-hidden md:w-100 md:h-100'>
            <Image 
              className='animate-pulse'
              src={deved} layout="fill" 
              objectFit='Cover' 
              />
          </div>
        </section>
        <section className='py-10'>
          <div>
          <h3 className='text-3xl font-bold text-center py-2 capitalize dark:text-white '>
            services that i offer
          </h3>
          <p className=' text-md py-3 leading-8 text-gray-800 dark:text-white '>
            Since the beginning of my journey as a web designer & Developer in Germany, i have done <span className='text-teal-500'>remote task </span>and worked 2 years almost as a professional <span className=' text-teal-500 font-bold'>frontend web designer</span> in Bangladesh, and now i'm learning backend as well. 
          </p>
          <p className=' text-md py-3 leading-8 text-gray-800 dark:text-white '>
            I offer from a wide range of services, including programing and design for <span className=' text-teal-500'>web applications.</span>
          </p>
          </div>
          <div className='lg:flex gap-10 py-10'>
            <div className='text-center shadow-xl p-10 mb-10 dark:bg-white dark:rounded-lg transition-all duration-300 hover:translate-y-10 cursor-pointer'>
              <Image className='mx-auto py-3' src={design} width={100} height={100}/>
              <h3  className=' lg:text-2xl font-bold'>Web Design</h3>
              <p className='py-3'>Creating elegant designs and static websites suited for your new design theory</p>
              <h4 className='py-4 text-teal-500'>Design tools that i used</h4>
              <p className='text-gray-800 py-2'>CMS : WordPress, webflow</p>
              <p className='text-gray-800 py-2'>Html, Css</p>
              <p className='text-gray-800 py-2'>JavaScripts es6</p>
              <p className='text-gray-800 py-2'> Jq plugins</p>
            </div>
            <div className='text-center shadow-xl p-10 mb-10 dark:bg-white dark:rounded-lg transition-all duration-300 hover:translate-y-10 cursor-pointer'>
              <Image className='mx-auto py-3' src={code} width={100} height={100}/>
              <h3  className=' lg:text-2xl font-bold'>Web Development</h3>
              <p className='py-3'>Creating elegant designs and dynamic sites suited for your new development theory</p>
              <h4 className='py-4 text-teal-500'>FrameWork that i used</h4>
              <p className='text-gray-800 py-2'>Tailwind CSS</p>
              <p className='text-gray-800 py-2'>Next.js</p>
              <p className='text-gray-800 py-2'>Bootstrap 5</p>
            </div>
            <div className='text-center shadow-xl p-10 mb-10 dark:bg-white dark:rounded-lg transition-all duration-300 hover:translate-y-10  cursor-pointer'>
              <Image className='mx-auto py-3' src={consulting} width={100} height={100}/>
              <h3 className=' lg:text-2xl font-bold'>CMS </h3>
              <p className='py-3'>Creating elegant designs suited for your new design theory</p>
              <h4 className='py-4 text-teal-500'>Wordpress</h4>
              <p className='text-gray-800 py-2'>Elementor</p>
              <p className='text-gray-800 py-2'>Webflow</p>
              <p className='text-gray-800 py-2'>Woo-Commerce</p>
              <p className='text-gray-800 py-2'>Shopify</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl text-center font-bold py-2 capitalize dark:text-white '>
              Portfolio
             </h3>
            <p className=' text-md py-3 leading-8 text-gray-800 dark:text-white '>
            Since the beginning of my journey as a freelance designer and developer, i have done <span className='text-teal-500'>remote task </span>and worked 2 years almost as a professional <span className=' text-teal-500 font-bold'>frontend web designer</span> in Bangladesh, and now i'm learning backend as well. 
            </p>
            <p className=' text-md py-3 leading-8 text-gray-800 dark:text-white '>
            I offer from a wide range of services, including programing and design for <span className=' text-teal-500'>web applications.</span>
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='group relative cursor-pointer items-center justify-center overflow-hidden transition-shadow hover:shadow-xl hover:shadow-black/30 basis-1/3 flex-1'>
            <div class=" transition-all">
             <Image src={agency} className={'rounded-lg  object-cover cursor-pointer'} width={'100%'} height={'100%'} layout={'responsive'}/>
            </div>
            <div class="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-black group-hover:from-black/70 group-hover:via-black/60 group-hover:to-black/70"></div>
            <div class="absolute inset-0 flex opacity-0 translate-y-[60%] flex-col items-center justify-center px-9 text-center transition-all duration-500 group-hover:opacity-100 group-hover:translate-y-0">
              <h1 class="font-dmserif text-3xl font-bold text-white">Agency</h1>
              <p class="mb-3 text-lg italic text-white opacity-0 transition-opacity duration-300 group-hover:opacity-100">Agency portfolio design with Html, Css3, Bootstrap, js, Jq</p>
              <a href='https://mkhaque1.github.io/agency-website/' target="_blank" class="rounded-full bg-neutral-900 py-2 px-3.5 font-com text-sm capitalize text-white shadow shadow-black/60">Live</a>
            </div>
            </div>
            <div className='group relative cursor-pointer items-center justify-center overflow-hidden transition-shadow hover:shadow-xl hover:shadow-black/30 basis-1/3 flex-1'>
            <div class=" transition-all">
             <Image src={nipro} className={'rounded-lg  object-cover cursor-pointer'} width={'100%'} height={'100%'} layout={'responsive'}/>
            </div>
            <div class="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-black group-hover:from-black/70 group-hover:via-black/60 group-hover:to-black/70"></div>
            <div class="absolute inset-0 flex opacity-0 translate-y-[60%] flex-col items-center justify-center px-9 text-center transition-all duration-500 group-hover:opacity-100 group-hover:translate-y-0">
            <h1 class="font-dmserif text-3xl font-bold text-white">Nipro</h1>
            <p class="mb-3 text-lg italic text-white opacity-0 transition-opacity duration-300 group-hover:opacity-100">More project visit mkhaque.com</p>
            <a href='https://mkhaque.com' target="_blank" class="rounded-full bg-neutral-900 py-2 px-3.5 font-com text-sm capitalize text-white shadow shadow-black/60">Live</a>
            </div>
            </div>
            <div className='group relative cursor-pointer items-center justify-center overflow-hidden transition-shadow hover:shadow-xl hover:shadow-black/30 basis-1/3 flex-1'>
            <div class=" transition-all">
             <Image src={product} className={'rounded-lg  object-cover cursor-pointer'} width={'100%'} height={'100%'} layout={'responsive'}/>
            </div>
            <div class="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-black group-hover:from-black/70 group-hover:via-black/60 group-hover:to-black/70"></div>
            <div class="absolute inset-0 flex opacity-0 translate-y-[60%] flex-col items-center justify-center px-9 text-center transition-all duration-500 group-hover:opacity-100 group-hover:translate-y-0">
            <h1 class="font-dmserif text-3xl font-bold text-white">Product</h1>
            <p class="mb-3 text-lg italic text-white opacity-0 transition-opacity duration-300 group-hover:opacity-100">Product landing page design with Html, Css3, Bootstrap5</p>
            <a href='https://mkhaque1.github.io/Camera-products/' target="_blank" class="rounded-full bg-neutral-900 py-2 px-3.5 font-com text-sm capitalize text-white shadow shadow-black/60">Live</a>
            </div>
            </div>
            <div className='group relative cursor-pointer items-center justify-center overflow-hidden transition-shadow hover:shadow-xl hover:shadow-black/30 basis-1/3 flex-1'>
            <div class=" transition-all">
             <Image src={travel} className={'rounded-lg  object-cover cursor-pointer'} width={'100%'} height={'100%'} layout={'responsive'}/>
            </div>
            <div class="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-black group-hover:from-black/70 group-hover:via-black/60 group-hover:to-black/70"></div>
            <div class="absolute inset-0 flex opacity-0 translate-y-[60%] flex-col items-center justify-center px-9 text-center transition-all duration-500 group-hover:opacity-100 group-hover:translate-y-0">
            <h1 class="font-dmserif text-3xl font-bold text-white">Travel Agency</h1>
            <p class="mb-3 text-lg italic text-white opacity-0 transition-opacity duration-300 group-hover:opacity-100">Travel Agency portfolio design with Html, Css3, Bootstrap, Swiper-js, Jq</p>
            <a href='https://mkhaque1.github.io/travel_agency_project/' target="_blank" class="rounded-full bg-neutral-900 py-2 px-3.5 font-com text-sm capitalize text-white shadow shadow-black/60">Live</a>
            </div>
            </div>
            <div className='group relative cursor-pointer items-center justify-center overflow-hidden transition-shadow hover:shadow-xl hover:shadow-black/30 basis-1/3 flex-1'>
            <div class=" transition-all">
             <Image src={card} className={'rounded-lg  object-cover cursor-pointer'} width={'100%'} height={'100%'} layout={'responsive'}/>
            </div>
            <div class="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-black group-hover:from-black/70 group-hover:via-black/60 group-hover:to-black/70"></div>
            <div class="absolute inset-0 flex opacity-0 translate-y-[60%] flex-col items-center justify-center px-9 text-center transition-all duration-500 group-hover:opacity-100 group-hover:translate-y-0">
            <h1 class="font-dmserif text-3xl font-bold text-white">3d card</h1>
            <p class="mb-3 text-lg italic text-white opacity-0 transition-opacity duration-300 group-hover:opacity-100">3d Card design with vanila JavsScripts only and Gsap library</p>
            <a href='https://mkhaque1.github.io/3d-card-effects/' target="_blank" class="rounded-full bg-neutral-900 py-2 px-3.5 font-com text-sm capitalize text-white shadow shadow-black/60">Live</a>
            </div>
            </div>
            <div className='group relative cursor-pointer items-center justify-center overflow-hidden transition-shadow hover:shadow-xl hover:shadow-black/30 basis-1/3 flex-1'>
            <div class=" transition-all">
             <Image src={cardProduct} className={'rounded-lg  object-cover cursor-pointer'} width={'100%'} height={'100%'} layout={'responsive'}/>
            </div>
            <div class="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-black group-hover:from-black/70 group-hover:via-black/60 group-hover:to-black/70"></div>
            <div class="absolute inset-0 flex opacity-0 translate-y-[60%] flex-col items-center justify-center px-9 text-center transition-all duration-500 group-hover:opacity-100 group-hover:translate-y-0">
            <h1 class="font-dmserif text-3xl font-bold text-white">Weather App</h1>
            <p class="mb-3 text-lg italic text-white opacity-0 transition-opacity duration-300 group-hover:opacity-100">Weather app design with html css vanila javascripts.</p>
            <a href='https://mkhaque1.github.io/weather-app-2.0/' target="_blank" class="rounded-full bg-neutral-900 py-2 px-3.5 font-com text-sm capitalize text-white shadow shadow-black/60">Live</a>
            </div>
            </div>
          </div>
        </section>
      </main>
      <footer className='bg-gray-700 py-9 text-center'>
          <div className=' flex justify-center'>
          <h4 className='text-white'>Copyright@</h4><Link className='text-white' href="/contact">M M Khairul Haque</Link> 
          </div>
        </footer>
    </div>
  );
}
